### ISSUE TITLE
Backend - Pitmaster funktionalität

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#12]
Pitmasterfunktion im Backend inkl. JSON Schnittstelle fertigstellen.

**Comment by sochs** [comment]
Die aktuellen Pitmaster-Werte: active, value, set, channel und typ werden ja bereits im data.json übertragen. Soll ich die verfügbaren PID-Typen in einem eigenen pitmaster.json übertragen oder im settings.json. Dort hatten wir ja schon einen Platzpalter "pitmaster" eingerichtet. Wenn es für dich einfacher ist, kann ichs aber auch in pitmaster.json packen zusammen mit den aktuellen Werten aus data.json, damit du alles in einem json hast. Wobei die jetztigen Werte im data.json auch bleiben würden, also doppelt übertragen werden, damit sie auch bei der Kanalseite verfügbar sind.

**Comment by Phantomias2006** [comment]
Alles in data lassen/hinzufügen

**Comment by sochs** [comment]
Gut data belass ich, die PID-Settings pack ich aber in settings, nicht zu data, das wird mir sonst zu voll.

**Comment by sochs** [comment]
So, auch die Pitmaster-Schnittstelle ist bereit. Hol dir aus dem data.json als erstes diesen Teil

"pitmaster":{"channel":0,"pid":0,"value":0.00,"set":10.00,"active":false,"manuel":false}

Da hast du zum einen den gewählten Kanal, das gewählte PID-Setting (als ID), den aktuellen Pitmaster-Wert in %, die gewünschte Solltemperatur, ob er Pitmaster aktiv ist und ob manuell der Pitmaster-Wert vorgeben werden soll (boolean). Die 6 Attribute entweder alle in ein graues Hintergrundfeld "Pitmaster-Setting" oder jedes einzeln. 

Für "Pitmaster aktiv" und "Manuelle Vorgabe" bitte Switchs.
Für "Pitmaster-Wert (%)" und "Solltemperatur" bitte Eingabefelder, wobei der Pitmasterwert nur veränderbar ist, wenn die Manuelle Vorgabe true ist. Sollen wir die einstellbare Solltemperatur deckeln auf den Min/Max-Bereich des gewählten Kanals?
Für "Kanal" und "PID-Setting" machst du am besten Auswahllisten. Die verfügbaren PID-Settings-Namen bekommst du aus dem settings.json dort gibt es den Teil "pid":

"pid":[{"name":"SSR SousVide","id":0,"aktor":0,"Kp":165.00,"Ki":0.59,"Kd":1000.00,"Kp_a":100.00,"Ki_a":0.08,"Kd_a":5.00,"reversal":false,"DCmmin":0,"DCmmax":80},{"name":"TITAN 50x50","id":1,"aktor":1,"Kp":3.80,"Ki":0.01,"Kd":128.00,"Kp_a":6.00,"Ki_a":0.00,"Kd_a":10.00,"reversal":false,"DCmmin":22,"DCmmax":100},{"name":"TITAN 60x60","id":2,"aktor":1,"Kp":3.80,"Ki":0.01,"Kd":128.00,"Kp_a":6.20,"Ki_a":0.00,"Kd_a":5.00,"reversal":false,"DCmmin":33,"DCmmax":100}],

Die einzelnen PID-Settings sind jeweils als json-Objekt zusammengefasst. Die Reihenfolge im Array entspricht auch der Nummerierung im "pid"-Attribut, zusätzlich hat jedes Objekt noch eine ID mit der selben Nummerierung. Ist wie bei den Kanal-Daten im data.json. Bei der Auswahlliste von "PID-Settings" sollen dann die Namen der einzelnen Settings angezeigt werden. Im Hintergrund wird aber mit der ID gearbeitet und übermittelt. Geht das? Falls dir das Rausholen der Namen aus dem Array zu schwierig ist, kann ich dir diese auch nochmal extra in einem eigenen Array, mit der selben Reihenfolge, im settings.json übergeben.

Unterhalb der generellen Pitmasterattribute bitte ein weiteres graues Hintergrundfeld "PID-Setting" errichten in dem dann alle PID-Setting-Werte drin stehen, und zwar von dem PID-Setting was im Auswahlfeld ausgewählt ist. Im Einzelnen sind das:

- "name": Eingabefeld mit der Bezeichnung "Name"
- "aktor": Auswahlliste mit der Bezeichnung "Aktorik", die verfügbaren stehen ebenfalls im settings.json unter "aktor":["SSR","FAN"], im Hintergrund bitte mit der Nummer arbeiten und den entsprechenden Text nur anzeigen.
- "Kp": Eingabefeld
- "Ki": Eingabefeld
- "Kd": Eingabefeld
- "Kp_a": Eingabefeld
- "Ki_a": Eingabefeld
- "Kd_a": Eingabefeld
- "DCmin": Eingabefeld mit der Bezeichnung "Duty Cycle (%) min"
- "DCmax": Eingabefeld mit der Bezeichnung "Duty Cycle (%) max"
- "reversal": Switch mit der Bezeichnung "Ansteuerung umkehren"

Klappt das mit der Verabeitung der IDs im Hintergrund und der Anzeige des PID-Setting-Namens und des Aktor?

Für das Speichern der Werte nimmst du dir bitte das "pitmaster" json-Objekt aus data.json und hängst da drin als weiteres Objekt "setting" das entsprechende PID-Setting json-Objekt an, welches ausgewählt wurde. Und schickst es an "setpitmaster" als POST. Sollte also so aussehen:

{"channel":0,"pid":0,"value":0.00,"set":10.00,"active":false,"manuel":false},"setting":{"name":"SSR SousVide","id":0,"aktor":0,"Kp":165.00,"Ki":0.59,"Kd":1000.00,"Kp_a":100.00,"Ki_a":0.08,"Kd_a":5.00,"reversal":false,"DCmmin":0,"DCmmax":80}}

Und hier die bin:
[Nemesis_v0.2.4.bin.zip](https://github.com/Phantomias2006/Nemesis/files/1048339/Nemesis_v0.2.4.bin.zip)

Nicht wundern, wenn die Nano beim ersten Start zweimal neustartet, ich hab den EEPROM aufgeräumt und umstrukturiert.

**Comment by Phantomias2006** [comment]
Ich mach hier mal dicht :-)
Sollte ja nun funktionieren.
