### ISSUE TITLE
Frontend - Pitmaster Reiter

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#13]
Neuen Reiter für Pitmaster erstellen.
Voraussetzung:
JSON Schnittstelle - #12 @sochs
Abklärung welche Eingabefelder benötigt werden

**Comment by sochs** [comment]
Bzgl. Eingabefelder. Der Pitmaster selbst hat die Eingabefelder:

- Kanal (Dropdown)
- Solltemperatur (numerischer Wert)
- aktiv (boolean)
- manuell (numerischer Wert 0-100)
- PID-Setting (Dropdown)

 Jedes PID-Setting hat aktuell folgende (vom User veränderbare) Parameter:

- name
- Kp;                     // P-Konstante oberhalb pid_switch
- Ki;                     // I-Konstante oberhalb pid_switch
- Kd;                     // D-Konstante oberhalb pid_switch
- Kp_a;                   // P-Konstante unterhalb pid_switch
- Ki_a;                   // I-Konstante unterhalb pid_switch
- Kd_a;                   // D-Konstante unterhalb pid_switch
- pid_switch;                // Umschaltungsgrenze
- freq;                  // Ansteuerung mit 1/pause Hz oder 4kHz 

Die Parameter: Pause, Ki_min, Ki_max würde ich festsetzen für alle Profile. Was ich noch nicht habe, aber für Lüfter noch brauche sind die Parameter pwm_min und pwm_max. 

Ich kann bis zu 5 Profile in der Nano speichern. Entweder ich gebe 5 Dummy-Profile out-of-the-box vor, die vom User über die Eingabefelder überschrieben werden können, oder es gibt einen Button  "neues Profil anlegen" mit dem ein neues Profil erstellt wird. Dann muss ich beim 6 Profil aber eins rauswerfen. Variante 1 gefällt mir besser.

Ansonsten noch einen Button zum Starten des Autotune.
Mal sehen, ob mir nochwas einfällt.

**Comment by Phantomias2006** [comment]
Hast du eventuell auch Designtechnische "Vorschläge" wie das aussehen kann?
Die Profile mittels PullDown? Kann mir das noch nicht recht vorstellen...

**Comment by sochs** [comment]
Nicht Pulldown, sondern Dropdown, ich meinte einfach sowas wie bei Sprache unter System. Ich bastel mal ein Paint-Design zusammen. Würde das aber halten wie bei System oder Kanalsettings auch.

**Comment by sochs** [comment]
Siehe Hinweis unter #12
