### ISSUE TITLE
Firmwareupdate über HTTP

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#14]
Mittels Arduino Core sollte ein Firmwareupdate auch über einen http Server funktionieren.
[http://esp8266.github.io/Arduino/versions/2.0.0/doc/ota_updates/ota_updates.html#http-server](url)
Denkbar wäre dass das GUI auf GITHUB überprüft ob ein neues Firmwareupdate ansteht und den Downloadlink an das Backend weiter gibt.
Macht diese funktion Sinn?

Bitte bei Gelegenheit folgendes klären:
Funktioniert der Download und das Flashen der Firmware über den Direktlink auf GIT
Funktioniert der Download und das Flashen des SPIFFS über den Direktlink auf GIT

**Comment by sochs** [comment]
Also für Firmware kann ich die Tage mal ausprobieren, beim Flashen der SPIFFS bin ich mir unsicher.

**Comment by Phantomias2006** [comment]
Du brauchst dir nicht unsicher sein ;-)
[https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266httpUpdate/examples/httpUpdateSPIFFS/httpUpdateSPIFFS.ino](url)

Ich überlege aber immer noch ob es nicht Sinnvoller ist wenn die "Versionsprüfung" nicht das Frontend sondern das Backend macht.
Theoretisch kann es ja sein dass das Thermo keine Internetverbindung hat aber das handy schon. Dann würde die Updatenotification kommen und das Thermo kann sich aber nicht aktualisieren. Wie denkst du darüber?

**Comment by sochs** [comment]
Also im Sinn: Backend checkt selbst nach Update und zeigt im Frontend nur an, dass eins verfügbar ist. Der User bestätigt dann quasi nur. Find ich auch sinnvoller.

**Comment by Phantomias2006** [comment]
Richtig. Du übergibst mir einfach ein Updateflag inkl. Link zur Releasenote.
GIT hat ein ATOM Feed. Da bekommst du alle Infos. Gibt auch ein "latest release" wenn ich mich recht erinnere. Die RepoUrl sollte dann aber im EEPROM liegen und eventuell konfigurierbar werden.

**Comment by sochs** [comment]
https://github.com/WLANThermo-nano/WLANThermo_nano_Software/releases.atom

https://api.github.com/repos/WLANThermo-nano/WLANThermo_nano_Software/releases/latest
https://developer.github.com/v3/repos/releases/

**Comment by Phantomias2006** [comment]
Kannst du so große Files im Speicher halten und bearbeiten oder soll ich das im Frontend machen?

**Comment by sochs** [comment]
Bin noch nicht ganz sicher was der beste Weg ist. Habe hier mal ein Beispielprojekt gefunden, bei dem auch auf ein Git Repro zugegriffen wird: https://blog.squix.org/2016/06/esp8266-continuous-delivery-pipeline-push-to-production.html

Der Git-Link zur bin ist halt https, damit ich darauf zugreifen kann brauch ich zudem einen fingerprint. Im Besipiel wird das über ein php gelöst, was als Zwischenglied fungiert. Das Umzubauen auf unser Repro wär nicht schwierig. Wir müssten es nur irgendwo laufen lassen. Theoretisch müsste doch das Frontend auch das php abfragen können, und bei einem verfügbaren Update ein Flag ans Backend geben, so dass dieses auch das php abfragt. Oder kann das Frontend die Aufgabe vom php komplett übernehmen?

**Comment by Phantomias2006** [comment]
Kannst du vl mal ein Firmwareupdate versuchen?
[https://github.com/WLANThermo-nano/WLANThermo_nano_Software/releases/download/v0.3/Nemesis_v0.3.bin](url)
Dann sehen wir auch gleich ob wir PHP brauchen oder nicht. 
Einfach einmal starr in das Backend Programmieren. Bei Systemstart soll er sich das File holen und Flashen.

**Comment by sochs** [comment]
Schon versucht, auch http, funktioniert nicht. Das Thema https und fingerprint wird hier thematisiert:
https://github.com/esp8266/Arduino/issues/2022

**Comment by Phantomias2006** [comment]
Machen wir auch einen "Automatisch nach Updates suchen" Checkbox ins GUI?
Und nur wenn "true" dann sucht das Backend nach Updates beim starten?

**Comment by sochs** [comment]
Können wir machen, dann setzten wir das aber default auf true.

**Comment by Phantomias2006** [comment]
Passt.
Kannst du die /update noch mittels auth schützen?

**Comment by Phantomias2006** [comment]
Bitte noch eine Schnittstelle "updatestatus" machen. Diese brauche ich für die Ladeanimation.
Und das auch noch:
Kannst du die /update noch mittels auth schützen?

**Comment by sochs** [comment]
Erledigt.
