### ISSUE TITLE
Nachkommastellen Temperaturwerte

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#15]
Derzeit werden 2 Nachkommastellen angezeigt und Alex möchte nur 1ne Nachkommastelle anzeigen.
Folgendes muss geklärt werden:
Macht 1Nachkommastelle Sinn?
Wo soll das runden passieren? (Backend/Frontend)

@sochs 
Brauchst du beide Nachkommastellen für die Pitmasterberechnung?

Hier ein Beispiel wie die Nachkommastelle im GUI gerundet werden kann:
`
		var f="22.45";
		f = parseFloat(f).toFixed(1);
`

**Comment by sochs** [comment]
Also die Nano rechnet weiterhin intern alles mit float, nur die Ausgabe ins Json habe ich jetzt auf 1 Nachkommastelle begrenzt. So hat das Backend die Kontrolle darüber und nicht jedes Frontend muss sich um die Rundung kümmern. 

Bei der Solltemperaturvorgabe an den Pitmaster denk ich reicht auch 1 Nachkommastelle, wobei das ein eigenes Attribut ist, was wir auch mit 2 Nachkommastellen im json darstellen könnten, falls gewünscht.

**Comment by Phantomias2006** [comment]
Gut, dann schließe ich hier :-)
