### ISSUE TITLE
Hardwarealarm-Anzeige wird nicht aktualisiert

### ISSUE THREAD

**Issue by sochs** [Phantomias2006/Nemesis#16]
Die Hardwarealarm-Anzeige wird nicht aktualisiert wenn eine Änderung an Backend vorgenommen wird. Im settings-json steht der richtige Wert, dieser wird von der Anzeige aber nicht angenommen. Ein verändern des Attributs im Backend durch eine Eingabe im Frontend ist jedoch möglich.

**Comment by Phantomias2006** [comment]
Hier macht der Slider Probleme. Das übergeben der Werte funktioniert. Ich schaue mir das Thema an.

**Comment by Phantomias2006** [comment]
Falls du zufällig gerda ein System zum testen hast dann tausche die showSystem function gegen:
`	function showSystem(){`
`		hideAll();`
`		loadJSON('settings', '', function (response) {`
`			jsonresponse = JSON.parse(response);`
`			document.getElementById('timezone').value = jsonresponse.system.utc;`
`			document.getElementById('language').value = jsonresponse.system.language;`
`			document.getElementById('hostname').value = jsonresponse.system.host;`
`			document.getElementById('unit').value = jsonresponse.system.unit;`
`			if (jsonresponse.system.hwalarm == true){`
`				document.getElementById('hwalarm').checked == true;`
`			}else{`
`				document.getElementById('hwalarm').checked == false;`
`			}		`
`		})`
`		document.getElementById("system_config").style.display = "inline";`
`	}	`

**Comment by sochs** [comment]
Fast. Mit der geänderten showSystem() klappts auch nicht, aber mir ist aufgefallen, dass du dort statt des Attributs "value" das Attribut "checked" aufrufst. Wenn ich in der ursprünglichen showSystem() das Attribut ändere, klappts. 

Mir ist aufgefallen, dass die Alarm-Funktionalität auch in den Kanal-Settings noch fehlt. Kannst du das noch ergänzen? Ich habe zwar das Auslesen der Variable im json und setzen der Anzeige hinbekommen, aber beim Speichern mach ich irgendwas falsch, das müsste noch ergänzt werden.

**Comment by Phantomias2006** [comment]
Kannst du mir ein data JSON hier anhängen? 
Das anzeigen sollte aber funktionieren oder?
`document.getElementById('webalarm').checked = jsonresponse.channel[channel].alarm;`
Was musstest du ändern?

**Comment by Phantomias2006** [comment]
`			jsonresponse.channel[channel].alarm = document.getElementById('webalarm').checked;`
Funktioniert das über //alert.... in der setChannel function?

**Comment by sochs** [comment]
Klappt. Dachte ich müsste da auch mit einer IF-Abfrage arbeiten, wie beim Hardwarealarm.

**Comment by Phantomias2006** [comment]
Vermutlich kann das bei hwalarm auch raus. Ich glaub das ist ein relikt als du noch mit 0 und 1 arbeiten wolltest :-D
Kannst ja mal schnell testen bitte

**Comment by sochs** [comment]
Läuft.
