### ISSUE TITLE
Backend - Auth mit falscher Bezeichnung

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#19]
Bei der Authentifizierung im GUI meldet sich das User/PWD Feld mit "asyncesp"
Bitte auf WLANThermo Nano umstellen

**Comment by Phantomias2006** [comment]
Vermutlich Zeile 117
` header.concat("asyncesp");`

> _include/ESPAsyncWebServer/src/WebAuthentication.cpp

**Comment by sochs** [comment]
Hattest Recht. Ist angepasst.
