### ISSUE TITLE
Thingspeak Schlüssel 

### ISSUE THREAD

**Issue by aschaefer85** [Phantomias2006/Nemesis#25]
Ein extra Button für Theakspeak.
Da kann man ein Schlüssel hinterlegen und eine URL zur eigenen  privat bzw. publik Seite (erspart einem diese irgend wo extra zu speichern )

Eventuell auch einen Link für die Leute die überhaupt keinen Account haben. Das erspart den Leuten google 👍

**Comment by sochs** [comment]
Soll der Button/Reiter Thingspeak heißen oder einfach "Charts"? Innerhalb von Charts gibt es dann eine Rubrik "Thingspeak" mit den von dir angesprochenen Elementen. Die Idee mit den URLs find ich gut. Ich müsst den Link eventuell aber im SPIFSS ablegen, statt im EEPROM. Der EE ist schon recht voll und ich will mir den freihalten. Im SPIFFS gehen Daten beim GUI flashen halt verloren.

**Comment by aschaefer85** [comment]
Reicht im SPIFFS m.M. nach.
Ich würde es erst mal Thingspeak nennen wollen.
Später wenn wir mehr können, können wir es in Charts ändern. So bleibt das aber im ersten Step übersichtlich.

**Comment by Phantomias2006** [comment]
Welche Eingabefelder soll ich erstellen? Gibt es irgendwelche Beschränkungen für die Felder?

**Comment by sochs** [comment]
Wir brauchen ein Eingabefeld für den "Channel Write API Key" des Thingspeak Channels. Der Key ist normalerweise 16 Zeichen lang, sofern Thingspeak das nicht ändert. Und ich hätte gern noch ein Eingabefeld für einen "ThingHTTP API Key", ebenfalls 16 Zeichen. Falls wir den Link zum Kanal auch speichern wollen, dann dafür auch ein Feld "Channel URL". Den Direktlink zu www.thingspeak.com würde ich fest im Frontend reinpacken, als Hyperlink.

**Comment by sochs** [comment]
So, Schnittstelle ist vorbereitet: Im settings.json findest du jetzt:

"charts":{"TSwrite":,"TShttp":,"TSchID":}

den Inhalt von TSwrite bitte ins Feld "Channel Write API Key", 
den Inhalt von TShttp bitte ins Feld "ThingHTTP API Key"
und den Inhalt von TSchID bitte ins Feld "Channel ID"
Darunter noch ein Switch "Public View", der ist nicht für mich, sondern für dich, deshalb kein Gegenstück im json. Die übergebenen Werte sind alles Strings.

Darunter oder daneben ein Hyperlink zu Thingspeak generell: https://thingspeak.com/
Und falls unter Channel ID eine ID eingetragen ist bitte noch ein Link zusätzlich anzeigen:
https://thingspeak.com/channels/"id"/private_show falls der Switch off ist, ansonsten
https://thingspeak.com/channels/"id"/ falls der Channel public ist.

Solltest du ja so umsetzen können? Das gute für mich, ich brauche nur die Channel ID speichern, was ich auch im EE machen kann. Der Link ist immer nach dem selben Schema aufgebaut.

Als Rückgabe bitte den Inhalt von "charts" aus dem settings.json, wie bei "system" auch. An "setcharts" also POST. Antwort auf den Request wie immer.

Zeichenbegrenzung für die ersten beiden ist 16 Zeichen. Bei der ID bin ich nicht sicher ob die immer 6 Zeichen lang ist.

Anbei die bin. Im dev Branch ist es auch.

Wollt ihr die Senderate als Angabe in Sekunden auch einstellbar machen, oder soll ich die fixen wie bisher? Falls ja bekommst du noch ein Attribut "TSrate".
[Nemesis_v0.2.3.bin.zip](https://github.com/Phantomias2006/Nemesis/files/1047595/Nemesis_v0.2.3.bin.zip)

**Comment by sochs** [comment]
Jungs, wie wollen wir das machen: Thingspeak hat ja (nur) 8 Messkanäle. Soll ich alle 8 Temperaturkanäle der Nano an die 8 Kanäle senden, oder nur 1-7 und Battery oder 1-5+7+8 (2 Dualkanäle + 3 Single) und Battery, oder soll es über das Frontend einstellbar sein. Also 9 Checkbuttons wovon aber nur 8 true gesetzt werden können. Die Kanalnummern passen dann halt nicht mit den Kanalnummern in Thingspeak, am ehesten noch bei der Variante 1-7 + Battery. Oder ich mach default 8x Temperatur und wir machen 1 Checkbox mit der man Kanal 8 mit Battery überschreiben kann.

**Comment by Phantomias2006** [comment]
Letzer Vorschlag. 1Checkbox wo Kanal 8 mit Battery überschrieben wird. Den machen wir in den Thingspeak reiter und ist default aus. Erweiterst du das Json?

**Comment by sochs** [comment]
Bitte. Attribut heißt "TSshow8", kann true/false.

[Nemesis_v0.2.7.bin.zip](https://github.com/Phantomias2006/Nemesis/files/1052949/Nemesis_v0.2.7.bin.zip)

**Comment by Phantomias2006** [comment]
Ich habe das jetzt eingebaut. Wert wird gespeichert. Leider kommt bei Thingspeak nichts an

**Comment by sochs** [comment]
Erledigt.
