### ISSUE TITLE
Help Button

### ISSUE THREAD

**Issue by aschaefer85** [Phantomias2006/Nemesis#26]
Help Button der zur GitHub Doku weiter leitet

**Comment by Phantomias2006** [comment]
Werde ich mir ansehen. Die Iedee ist super. Die Priorität derzeit aber gering :-)

**Comment by aschaefer85** [comment]
Das ist ja das Gute an der Idee ;-)
Du kannst jetzt eine under construction anlegen und da drauf einen href legen.
Später (und das kann nach dem Release sein) kümmern wir uns dann drum und brauchen keine Updates.

**Comment by Phantomias2006** [comment]
Sollte abgeschlossen sein
