### ISSUE TITLE
Zeitzone zu gering gewählt 

### ISSUE THREAD

**Issue by aschaefer85** [Phantomias2006/Nemesis#27]
Nur +1 und -1 Stunde ist sehr sparsam.

**Comment by Phantomias2006** [comment]
Sollen die möglichen Zeitzonen im Backend liegen und über ein Json übertragen werden?

**Comment by sochs** [comment]
Warum? Zeitzonen sind doch klar definiert. Du kannst die Eingabe also einfach auf -12h bis +12h erweitern und mir den Wert wie bisher schicken.

**Comment by sochs** [comment]
Was machen wir mit Sommer und Winterzeit? Soll das der User einfach per Anpassung der Zeitzone korrigieren?

**Comment by Phantomias2006** [comment]
Kann das Backend bzw. die NTC Lib Sommer/winterzeit automatisch erkennen?

**Comment by Phantomias2006** [comment]
Die Zeitzone ist nun erweitert. Für die Sommer/Winterzeit gegebenenfalls ein neues Issue aufmachen.

**Comment by sochs** [comment]
Nicht über NTP, da bekomme ich nur UTC. Ich müsste eine weitere Abfrage machen, z.B. hierauf:
http://www.netzwolf.info/astronomie/ephemeriden/sonne
Das gilt dann aber nur für unsere Zeitzone, und nicht überall gibt es Sommer- und Winterzeit. 
Alternativ zur Anpassung der Zeitzone könnten wir auch einen Switch machen, wo der User Sommerzeit zu/abwählen kann.

**Comment by sochs** [comment]
Hab ein neues Issue #31 aufgemacht.
