### ISSUE TITLE
Cursoränderung beim Überfahren der verfügbaren SSIDs

### ISSUE THREAD

**Issue by sochs** [Phantomias2006/Nemesis#28]
Besteht die Möglichkeit, dass sich der Cursor von Texteingabe zu Pfeil ändert, sobald man über eine der SSIDs in der Liste drübergeht? Ansonsten hat man nicht den Eindruck, dass man dort etwas auswählen kann.

**Comment by Phantomias2006** [comment]
Werde ich prüfen.

**Comment by Phantomias2006** [comment]
Kannst du bitte folgendes testen:
`.wlantable tr {`
`cursor: pointer;		`
`}`

Das ganze unterhalb von:

		.wlantable td {
		max-width: 0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		}
einfügen. (Zeile 1622 im aktuellen dev branch)

**Comment by Phantomias2006** [comment]
Funktioniert

**Comment by sochs** [comment]
Sehr gut. Wär es noch möglich den Hintergrund hinter der überfahrenen SSID hellgrau einzufärben? Falls das zu aufwendig ist, Issue wieder schließen.

**Comment by Phantomias2006** [comment]
Bitte testen und bei gefallen schließen

**Comment by sochs** [comment]
Gefällt mir.
