### ISSUE TITLE
WLAN-Speicher-löschen-Switch

### ISSUE THREAD

**Issue by sochs** [Phantomias2006/Nemesis#29]
Der Switch oberhalb der verfügbaren SSIDs ist noch ohne Funktion. Der soll ja eigentlich zum Löschen der WLAN-Daten im EEPROM da sein. Dort wo er jetzt ist, wirkt er aber eher wie ein WLAN on/off Schalter. Ich finde die Funktion im Reiter WLAN schon sinnvoll. Würde zwar auch unter System gehen, aber ich glaub dann findet es keiner, wenn es mal gebraucht wird. Aber vll sollten wir einen Button draus machen, und keinen Switch. Was denkt ihr?

**Comment by Phantomias2006** [comment]
Der Button war tatsächlich ein WLAN ON/OFF Switch. Erinnerst du dich nicht mehr? Damit wollten wir/Alex das Wlan deaktivieren zum Batteriesparen bis zum nächsten reboot

**Comment by sochs** [comment]
Ah ok. Dann passt der dort. Das mit dem on/off ist nur so eine Sache. Ohne Restart ist das nie sauber. Ich schau es mir aber nochmal an.

Würdest du dann noch einen Button "WLAN-Settings löschen" hinzufügen?

**Comment by Phantomias2006** [comment]
Sollen wir on/off rausnehmen?
Der Sinn ist für mich immer noch fragwürdig?!

**Comment by aschaefer85** [comment]
Bitte drinnen lassen.
WLAN ausschalten macht Sinn wenn man Akku sparen möchte und eh in der Nähe vom Gerät ist. Nach einem Neustart kann der gerne wieder von alleine aktiviert werden

**Comment by sochs** [comment]
Also ich habe jetzt einen POST Request "stopwifi" ergänzt, mit dem wird das Wifi-Modul abgeschaltet. Nach einem Restart des Systems funktioniert es wieder ganz normal. Der Request wird mit "OK" beantwortet. Also am besten den Switch so programmieren, dass er bei Betätigung den Request sendet. Geht das? Zurücksetzen kann man den Switch aber nicht, Verbindung ist dann ja weg.

**Comment by Phantomias2006** [comment]
Hast du noch einen Warntext der im GUI aufploppen soll?

**Comment by sochs** [comment]
Soll der vom Backend kommen? Oder willst du den im Frontend erzeugen und ich soll den Text liefern?

**Comment by Phantomias2006** [comment]
Nö, den erzeug ich im Frontend. Bin nur nicht kreativ :-)

**Comment by sochs** [comment]
Da reicht ja ein: "Wifi wirklich abschalten?" oder in lang: "Soll die Wifi-Verbindung bis zum nächsten Restart des Systems wirklich abgeschaltet werden?"

**Comment by sochs** [comment]
Für das Löschen des WLAN-Daten-Speichers habe ich jetzt einen POST-Request "clearwifi" eingefügt.

**Comment by Phantomias2006** [comment]
Hast du eine Idee wie und wo ich den clearwifi einbauen soll?

**Comment by sochs** [comment]
Mach doch einfach einen Button oder Switch im WLAN-Reiter, falls möglich auch ein Papierkork-Icon. Beim draufdrücken nochmal fragen ob der Speicher wirklich gelöscht werden soll und gut ist. Soll ich dafür am OLED auch eine Möglichkeit schaffen, wie beim Update? Doppelklick auf der SSID-Seite?
