### ISSUE TITLE
Fast-Mode in System-Settings aufnehmen.

### ISSUE THREAD

**Issue by sochs** [Phantomias2006/Nemesis#30]
Betrifft 
Backend: Integration in json.
Frontend: Switch erzeugen.

**Comment by Phantomias2006** [comment]
Für was ist Fastmode?

**Comment by aschaefer85** [comment]
Der lässt dann nur aktive Kanäle anzeigen.
Somit ist dann auch deine Idee mit der Kanal Seite auch über.
Wer möchte sieht alles und kann auch unbeschaltete Kanäle ändern. Wem das alles egal ist sieht nur das was wirklich beschaltet ist.

**Comment by sochs** [comment]
Liegt jetzt im EEPROM, muss als nächstes noch ins json.

**Comment by sochs** [comment]
Ist drin. Frontend-Anpassung kommt in neuem Issue zu verändertem Settings.json
