### ISSUE TITLE
Sommer- und Winterzeit

### ISSUE THREAD

**Issue by sochs** [Phantomias2006/Nemesis#31]
Nicht über NTP, da bekomme ich nur UTC. Ich müsste eine weitere Abfrage machen, z.B. hierauf:
http://www.netzwolf.info/astronomie/ephemeriden/sonne
Das gilt dann aber nur für unsere Zeitzone, und nicht überall gibt es Sommer- und Winterzeit.
Alternativ zur Anpassung der Zeitzone könnten wir auch einen Switch machen, wo der User Sommerzeit zu/abwählen kann.

**Comment by Phantomias2006** [comment]
Dann machen wir den Switch. Bitte mit true/false in der Schnittstelle

**Comment by sochs** [comment]
Ist drin. Ich mach ein neues Issue auf, da ich noch mehr im settings.json geändert habe.

**Comment by sochs** [comment]
Zur Dokumentation falls wir es doch irgendwann mal brauchen, es gibt eine Timezone Lib:
https://github.com/JChristensen/Timezone
Die ist aber speicherintensiv, weshalb ich gern drauf verzichten würde.
