### ISSUE TITLE
Datenabruf Windows Phone funktioniert nicht

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#32]
Laut Steffen gibt es Probleme beim Datenabruf am WindowsPhone. Temp Werte etc. werden nicht geladen.
Die Probleme treten erst auf seit ich bei xmlhttprequest ein timout hinzugefügt habe.
Die Zeile
`xobj.timeout = 1000;`
muss bei WP unterhalb
`xobj.open('POST', url, true);`
stehen.

Eventuell das Timout auch auf 2000 stellen! 
Testweise kannst du auch 
`xobj.timeout = 1000;`
unterhalb von
`xobj.setRequestHeader("Content-Type", "application/json");`
geben.

**Comment by sochs** [comment]
Hab jetzt mehrere Tests durch. Ich kann den Fehler am WP nicht reproduzierbar herstellen. Mit Timeout hinter open und 1000 funktioniert es bei einer Nano direkt. Bei der andern nicht. Geh ich dann auch 3000 geht es auch bei der. Geh ich wieder runter auf 1000 geht es nun auch bei dieser, wo es vorher nicht ging. Keine Ahnung was da schief läuft. Hinter open läuft jetzt aber immerhin bei ie und firefox auf meinem Laptop immer stabil. Hinter setRequest mochte WP auch nicht. Ich würd sagen wir lassen es jetzt auf 2000 und hinter open. Falls nochmal einer ein Problem damit hat, muss er es sich halt auskommentieren.
Habs in dev commited. Schließen?

**Comment by Phantomias2006** [comment]
Dann stell den Timeout auf 2000 und schließe das Issue.
Falls nötig öffnen wir es wieder.
