### ISSUE TITLE
Frontend - Logo wird teilweise nicht geladen

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#33]
Anscheinend gibt es teilweise ein Problem beim Datenzugriff. Das Thermo Logo oben links wird teilweise nicht geladen beim offnen/refresh der Seite. Der Webserver kommt hier teilweise mit Zugriff auf mehreren Files nicht klar. 

Folgendes klären:
Können wir am Webserver noch was verbessern? ( @sochs )
Können wir das Bild binär in der index.html speichern ( @Phantomias2006)

**Comment by Phantomias2006** [comment]
Den Frontend part habe ich schon umgesetzt - siehe DEV
Solltest du (@sochs) nichts mehr am Backend verbessern können bitte schließen.

**Comment by sochs** [comment]
Läuft. Am Backend wüsst ich erstmal nichts zu Ändern.
