### ISSUE TITLE
Anpassung des settings.json

### ISSUE THREAD

**Issue by sochs** [Phantomias2006/Nemesis#34]
So, das settings.json hat sich gändert zu:

{"system":{"time":"1496323986","utc":1,"summer":false,"ap":"NANO-AP","host":"BOOM-Operator","language":"de","unit":"C","hwalarm":false,"fastmode":false,"version":"V0.3","hwversion":V1},"sensors":["Maverick","Fantast-Neu","100K6A1B","100K","SMD NTC","5K3A1B","MOUSER47K","Typ K"],"pitmaster":["SSR"],"charts":{"thingspeak":""},"hardware":["V1"]}

Neu hinzugekommen sind die Attribute "summer" (true/false), "fastmode" (true/false) und "hwversion".

Für "summer" = Sommerzeit und "fastmode" bitte einen Switch unter dem Reiter System anlegen. 

Für "hwversion" = Hardwareversion bitte ein Auswahlmenü anlegen, die möglichen Werte liefert die Nano ebenfalls im json unter "hardware".

Außerdem haben wir schon länger das Attribut "ap" im json. Lass uns dafür noch ein Feld unter Host anlegen, wo man den AP-Namen ändern kann. Gleiche Zeichenbeschränkung wie beim Hostnamen.

Brauchen wir für den Fastmode noch eine andere Bezeichnung im GUI? z.B Schnelllauf. Und vll sollten wir Hardwarealarm in Piepser umbennen.

**Comment by Phantomias2006** [comment]
Dazu brauche ich bitte die neue BIN

**Comment by Phantomias2006** [comment]
Kann ich dir die Settings so übergeben:
`{"time":"1496345338","utc":1,"summer":false,"ap":"NANO-AP","host":"NANO-82e95f","language":"de","unit":"C","hwalarm":false,"fastmode":false,"version":"V0.3","hwversion":"V1"}`

**Comment by Phantomias2006** [comment]
> Brauchen wir für den Fastmode noch eine andere Bezeichnung im GUI? z.B Schnelllauf. Und vll sollten wir Hardwarealarm in Piepser umbennen.

Ich habe jetzt
Fastmode=Schnelllauf
Hardwarealarm=Summer
summer=Sommerzeit
gemacht. Ich hoffe das passt.

Soll der AP-Name unter Menüpunkt System?

**Comment by Phantomias2006** [comment]
Sollte alles drin sein. Eventuell kannst du @sochs einmal ein paar HW Version einfügen um zu sehen ob der gespeicherte selektiert wird etc.

**Comment by sochs** [comment]
Top! Machst du mir noch die Zeichenbegrenzung rein?

**Comment by sochs** [comment]
13 Zeichen bei Host- und AP- Name

**Comment by Phantomias2006** [comment]
Zeichenbeschränkung ist jetzt drin
