### ISSUE TITLE
Frontend - Pitmaster im Kanal anzeigen

### ISSUE THREAD

**Issue by sochs** [Phantomias2006/Nemesis#35]
Im data.json sind ja bereits die aktuellen Pitmaster-Werte verfügbar. Falls "active" = true bitte den Temperatursollwert ("set") und den Pitmasterwert ("value") in % im entsprechenden Kanal ("channel") anzeigen. Eventuell auch den Namen des gewählten PID falls wir dafür Platz haben. Den würde ich dir dann auch noch übergeben. Schau mal bitte, wo und wieviel Platz du dafür in den Kanalfeldern hast.

**Comment by Phantomias2006** [comment]
Ich schließe hier mal. Ist ja nun drin.
