### ISSUE TITLE
BUG - Frontend: Unter WP werden beim ersten Aufruf Eingabefelder falsch angezeigt

### ISSUE THREAD

**Issue by sochs** [Phantomias2006/Nemesis#37]
Wird ein Eingabefeld das erste mal dargestellt, so erscheint der Eingabetext und der Beschreibungstext im Feld gleichzeitig. Beim nächsten Aufruf der Einstellseite wird es richtig angezeigt,

**Comment by Phantomias2006** [comment]
Ich glaube ich habe den Bug jetzt behoben. Bitte testen und falls es nicht funktioniert Issue wieder öffnen.
