### ISSUE TITLE
Backend - Settings gehen nach Reboot verloren

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#38]
Gewisse Systemeinstellungen gehen nach einen Neustart verloren.
Hardwarealarm
Fastmode (da bin ich mir nicht sicher)
Die Werte werden korrekt gespeichert und laut Debug auch im EEProm richtig ausgelsen:

Hier beim aufruf und setzen von HWALARM
> [INFO]	Reading from EE: {"host":"NANO-82e95f","hwalarm":false,"ap":"NANO-AP","lang":"de","utc":0,"summer":true,"fast":true,"hwversion":1,"batmax":4185,"batmin":3600,"logsec":104}
[INFO]	Clear EEPROM from: 300 to: 549
[INFO]	Writing to EE: (154) {"host":"NANO-82e95f","hwalarm":true,"ap":"NANO-AP","lang":"de","utc":0,"summer":true,"fast":true,"hwversion":1,"batmax":4185,"batmin":3600,"logsec":104}
[INFO]	11:21:58 4.6.2017

Hier beim auslesen von HWALARM
> [INFO]	Reading from EE: {"host":"NANO-82e95f","hwalarm":true,"ap":"NANO-AP","lang":"de","utc":0,"summer":true,"fast":true,"hwversion":1,"batmax":4185,"batmin":3600,"logsec":104}
[INFO]	System config loaded

Und hier was über die JSON übertragen wird
> {"system":{"time":"1496575422","utc":0,"summer":true,"ap":"NANO-AP","host":"NANO-82e95f","language":"de","unit":"C","hwalarm":false,"fastmode":true,"version":"V0.3","hwversion":"V1"},"sensors":["Maverick","Fantast-Neu","100K6A1B","100K","SMD NTC","5K3A1B","MOUSER47K","Typ K"],"pid":[{"name":"SSR SousVide","id":0,"aktor":0,"Kp":165.00,"Ki":0.59,"Kd":1000.00,"Kp_a":100.00,"Ki_a":0.08,"Kd_a":5.00,"reversal":false,"DCmmin":0,"DCmmax":80},{"name":"TITAN 50x50","id":1,"aktor":1,"Kp":3.80,"Ki":0.01,"Kd":128.00,"Kp_a":6.00,"Ki_a":0.00,"Kd_a":10.00,"reversal":false,"DCmmin":22,"DCmmax":100},{"name":"TITAN 60x60","id":2,"aktor":1,"Kp":3.80,"Ki":0.01,"Kd":128.00,"Kp_a":6.20,"Ki_a":0.00,"Kd_a":5.00,"reversal":false,"DCmmin":33,"DCmmax":100}],"aktor":["SSR","FAN"],"charts":{"TSwrite":"488QLPLF6RMIR6M9","TShttp":"","TSchID":""},"hardware":["V1","V2"]}

**Comment by sochs** [comment]
Dürfte nur Hardwarealarm gewesen sein. Fehler gefunden. Falls doch noch ein anderes Attribut gefallen sein sollte, Issue wieder öffnen.
