### ISSUE TITLE
Umbau von float auf uint32_t

### ISSUE THREAD

**Issue by sochs** [Phantomias2006/Nemesis#40]
Eventuell alle float aus dem Code verbannen:
http://forum.arduino.cc/index.php?topic=210398.0

**Comment by Phantomias2006** [comment]
@becothal 
Wie würdest du das beurteilen? Macht es Sinn?

**Comment by sochs** [comment]
Hab mir das mal angesehen, bin der Meinung man gewinnt nicht viel, im Vergleich zum Aufwand, den man durch die nachträgliche Änderung (Speicherung im EE, Verarbeitung im Pitmaster, Übergabe an Webinterface/API) hat.

**Comment by Phantomias2006** [comment]
Gut, dann schließe ich das Ticket. Bei bedarf kann es wieder geöffnet oder ein neues erstellt werden.
