### ISSUE TITLE
Frontend - Buttons Menüführung

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#41]
Die Buttons der Menüführung soll folgendermaßen:
![nano](https://user-images.githubusercontent.com/15437240/27217983-72af92b6-527c-11e7-8799-0edb50990cf0.png)

 Die Icons dazu bitte in SVG Format erstellen und im WLANThermo_Icons Repository hochladen.
Bis diese eingebunden werden bitte im GUI "<" ">" verwenden.

Der "Back" Button soll immer ganz links stehen und der "Save" Button ganz rechts. Auch in der Desktopansicht.

**Comment by sochs** [comment]
Sollen wir das schließen Flo? Ist ja mit der v0.8.1 und den blauen Buttons quasi abgeschlossen.
