### ISSUE TITLE
Backend - Thingspeak

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#44]
Ich würde gerne Thingspeak Ein/Aus schalten können. Dazu brächte ich ein True/False flag.
Außerdem möchte ich das Sendeintervall konfigurierbar machen
30/60/120/180/240/300 Sekunden

**Comment by sochs** [comment]
Können wir zum Ausschalten auch einfach einen Eintrag im Sendeintervall machen, also 0? Wenn der Sendeintervall einen Wert ungleich 0 hat, ist dann ON. Du kannst 0 im Webinterface ja auch als OFF darstellen, dann sparen wir uns einen Switch.

**Comment by Phantomias2006** [comment]
Können ja, logischer ist es anders. Vl hab ich ja fix immer 180Sekunden eingestellt und will es nur schnell Ein/Aus schalten... aber suchs dir aus. Von der funktion her ist es egal...

**Comment by sochs** [comment]
Du hast ab v0.4.9 jetzt drei weitere Attribute im settings.json im Bereich "charts":
- "TSinterval" als int für die Einstellung der Sendezeit in sec
- "TSon" als bool um Thingspeak an = true / aus = false zu schalten
- "TSuser" als String für die Eingabe des USER KEY, brauchen wir, wenn wir Metdata bei TS nutzen wollen

Gesetzt werden die Variablen einfach wie die anderen über /setcharts

**Comment by sochs** [comment]
Sollen die möglichen Intervallzeiten von der Nano als Auswahl kommen oder machst du das einfach in Frontend?

**Comment by Phantomias2006** [comment]
Die Intervallzeiten mache ich im Frontend
