### ISSUE TITLE
WLAN Einwahlprozess

### ISSUE THREAD

**Issue by sochs** [Phantomias2006/Nemesis#45]
Überarbeitung der Eingabe der Wifi-Daten. Filterung beim Speichern nach lediglich neuen Daten. Eventuell eine Art "Schnellverbindung" zu bekannten Netzen übers GUI.

**Comment by sochs** [comment]
Testlauf der neuen Funktion in der v0.8.4. Umbau noch nicht komplett abgeschlossen.

**Comment by sochs** [comment]
Umbau mit v0.9.6 weitestgehend abgeschlossen.
Überlegung ob man noch die Möglichkeit auf ein manuelles Umschalten auf rein AP-Modus ermöglicht. Sinn: man befindet sich an der Schwelle zu einem bekannten WLAN und will vermeiden, dass die Nano sich verbindet und man die Verbindung zum NANO-AP verliert.

**Comment by Phantomias2006** [comment]
Falls manuelles Umschalten gewünscht wird bitte ein neues Ticket erstellen.
