### ISSUE TITLE
Backend - Telegram Notification

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#49]
Bitte eine Schnittstelle für das GUI anlegen für Telegram.
Folgende Parameter im EEProm speichern:
API Token
Chat ID
on/off

Du bekommst am Server dann eine
sendNotification.php
Schnittstelle von mir.

**Comment by sochs** [comment]
Ist drin: 

settings.json: "TGon", "TGtoken" und "TGid"
