### ISSUE TITLE
Server - Telegram Notification

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#50]
Es muss für Telegram eine Serverschnittstelle zwischen Nano und Telgram Programmiert werden.

**Comment by sochs** [comment]
Quasi fast umgesetzt mit der v0.8.0. Eventuell noch erweitern auf andere Dienste.

**Comment by sochs** [comment]
Erweiterung der Notification um niedrigen Akkustand.

**Comment by sochs** [comment]
Und Erweiterung der Notification um "Push aktiviert/deaktiviert" einbauen
