### ISSUE TITLE
Nano Cloud Graph um Batteriezustand erweitern

### ISSUE THREAD

**Issue by sochs** [Phantomias2006/Nemesis#55]
Erweiterung des Graphen um eine Batteriezustandskurve.

**Comment by sochs** [comment]
Bei der Farbe wäre ich für weiß.

**Comment by Phantomias2006** [comment]
Macht es überhaupt Sinn die Batterieanzeige zu Loggen?

**Comment by sochs** [comment]
Schon nicht verkehrt, um die Entladerate seines Akkus zu kennen. Wenn wir mal ein paar Entladeratekurven kennen, könnten wir eventuell auch mal eine lineare Anpassung versuchen, sodass die Batterieangabe linear zur Laufzeit wäre und nicht wie jetzt exponentiell
