### ISSUE TITLE
Energiesparmodus

### ISSUE THREAD

**Issue by sochs** [Phantomias2006/Nemesis#56]
- Aktivierbar über System Reiter im Webinterface
- temporäre Abschaltung des Wifi-Moduls
- temporäre Speicherung der Cloud Intervallsdaten
- reduziertes Sendeintervall (alle 3min oder 5min ausprobieren) mit Versand aller gespeicherter Daten
- Deaktivierung? Nur übers OLED möglich oder gibt es noch eine andere Idee.

**Comment by Phantomias2006** [comment]
Ist dieses Ticket noch aktuell?

**Comment by sochs** [comment]
Ich seh aktuell kein Bedarf dafür.
