### ISSUE TITLE
HTTP Firmware update - Versionsanzeige falsch bei fehler

### ISSUE THREAD

**Issue by Phantomias2006** [Phantomias2006/Nemesis#62]
Wenn bei FW update ein redirect (301) kommt wird die FW anzeige auf die neue FW gesetzt obwohl die FW nicht geladen werden konnte.

**Comment by Phantomias2006** [comment]
@sochs 
Haben wir dieses Problem bereits behoben bzw. kann es behoben werden?

**Comment by sochs** [comment]
Der Fehler ist mir nicht bekannt. Wenn ein FW Update nicht verfügbar ist, bleibt die FW auf dem alten Stand, auch die Anzeige. Allerdings, wenn das vorgelagerte SPIFFS Update klappen sollte, könnte dieses auf einer neuen Version sein, wohingegen die FW dann noch alt sein kann. Ist aber schon immer so und bisher war das kein Problem.
