### ISSUE TITLE
32 stellige SSID führt zu Fehlern beim Scan

### ISSUE THREAD

**Issue by IzeQube** [Phantomias2006/Nemesis#63]
Wenn eine 32 stellige SSID gefunden wird, funktioniert die Wifi-Auswahl im Frontend nicht mehr. 

Im JSON, was vom API-Aufruf **networklist** zurückgegeben wird, stehen hinter der SSID noch ein paar Unicode zeichen:
``
{"SSID":"12345678901234567890123456789012 Ñ","RSSI":-47,"Enc":4}
``

Eine Verbindung mit einem Wifi-Netz mit einer 32 stelligen SSID ist auch über die HTTP-API nicht möglich, vermute aber das dort der selbe Fehler auftritt.

**Comment by Phantomias2006** [comment]
Danke für deinen Bugreport. Sind in deiner SSID auch Sonderzeichen/Leerzeichen enthalten?

**Comment by IzeQube** [comment]
Nein, bei dem Test habe ich die SSID 12345678901234567890123456789012 genommen.

**Comment by sochs** [comment]
Fehlererklärung: Der ESP-Core gibt die 32 stellige SSID falsch aus (WiFi.SSID(i)) und liefert stattdessen eine für JSON nicht lesbare Zeichenkette, weshalb keine Anzeige im Webinterface erfolgt.

Fehlerbehebung: Erweiterung der Funktion _String ESP8266WiFiScanClass::SSID(uint8_t i)_ im ESP-Core (ESP8266WiFiScan.cpp) zu:

String ESP8266WiFiScanClass::SSID(uint8_t i) {
    struct bss_info* it = reinterpret_cast<struct bss_info*>(_getScanInfoByIndex(i));
    if(!it) {
        return "";
    }
	**char ssidBuffer[33] = {0};
	memcpy(&ssidBuffer[0], it->ssid, 32); 
	return String(ssidBuffer);**
}

Anschließend wird die SSID richtig eingelesen und kann somit auch im Webinterface dargestellt werden. Ein Verbinden ist dennoch nicht möglich, da in der Funktion ESP8266WiFiSTAClass::begin die Länge einer SSID auf 31 begrenzt ist. Daher muss folgende Änderung an der ESP8266WiFiSTA.cpp durchgeführt werden: 

if(!ssid || *ssid == 0x00 || strlen(ssid) > **32**) {
        // fail SSID too long or missing!
        return WL_CONNECT_FAILED;
}

Nun kann auch eine Verbindung zur 32 stelligen SSID aufgebaut werden, allerdings kann die Verbindung in der Nano-Firmware nicht gespeichert werden, da nun WiFi.SSID() noch eine falsche SSID (SSID+Passwort) ausgibt. Dies lässt sich wiederum beheben durch Erweiterung der Funktion _String ESP8266WiFiSTAClass::SSID()_ in der ESP8266WiFiSTA.cpp zu:

String ESP8266WiFiSTAClass::SSID() const {
    struct station_config conf;
    wifi_station_get_config(&conf);
	**char ssidBuffer[33] = {0};
	memcpy(&ssidBuffer[0], conf.ssid, 32); 
	return String(ssidBuffer);**
}

Im Anschluss lässt sich sowohl eine Änderung aufbauen, wie auch speichern.
