### ISSUE TITLE
Wiki: Tippfehler Update

### ISSUE THREAD

**Issue by obi134** [Phantomias2006/Nemesis#69]
Folgende Tippfehler:
"Softwareversion verfügbar ist**,** erscheint" (Komma versetzen)
"alle Softwareversion**en** ab "
"unbedingt beach**tet werden** sollte
"also unter **U**mständen Versionen"

**Comment by sochs** [comment]
Korrigiert. @obi134 vielen Dank für deine Mühe, die gefunden Fehler zu melden!
