### ISSUE TITLE
c_com.h:169: Zeile sinnlos?

### ISSUE THREAD

**Issue by obi134** [Phantomias2006/Nemesis#72]
```
// HTTP UPDATE
    else if (str == "update") {
      if (update.version != "false");  // Macht diese Zeile Sinn?
      update.state = 1;
      return;
    }
```

**Comment by sochs** [comment]
Macht Sinn. Beim Systemstart wird der Server nach einen Update abgefragt. Wenn ein Update vorhanden ist, dann steht die Version in update.version. Wird nun über die Serielle Schnittstelle der Befehl "update" gegeben, wird das Update nur gestartet, wenn auch ein Update da ist. Im Gegensatz dazu kann über den Befehl "update:vxx" ein Update auf eine bestimmte Version eingeleitet werden. Was hier "fehlt" ist die Einrückung der Zeile unterhalb von IF, wobei das der Compiler schon richtig erkennt.
Die Befehle über die Serielle Schnittstelle sind hauptsächlich fürs Debugging und Reserve.
